"""stimmprofile

Revision ID: b8c4e6f0a2d3
Revises: a7b3d5e9f1c2
Create Date: 2026-09-26 22:16:05.406212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c4e6f0a2d3'
down_revision: Union[str, Sequence[str], None] = 'a7b3d5e9f1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_jobs_owner_user_id'), ['owner_user_id'], unique=False)

    with op.batch_alter_table('voice_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('base_embedding', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('learned_sum', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voice_profiles', schema=None) as batch_op:
        batch_op.drop_column('embedding_model')
        batch_op.drop_column('learned_sum')
        batch_op.drop_column('base_embedding')
        batch_op.drop_column('consent_at')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_owner_user_id'))
        batch_op.drop_column('owner_user_id')

    # ### end Alembic commands ###
