"""sprecher_modellfassung

Revision ID: c9d5f7a1b3e4
Revises: b8c4e6f0a2d3
Create Date: 2026-09-27 00:16:19.909185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d5f7a1b3e4'
down_revision: Union[str, Sequence[str], None] = 'b8c4e6f0a2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('speakers', schema=None) as batch_op:
        batch_op.drop_column('embedding_model')

    # ### end Alembic commands ###
