"""kommentare_termine

Revision ID: f5b8d2e0c3a6
Revises: e4a7c1d9b2f5
Create Date: 2026-09-27 01:45:32.580548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b8d2e0c3a6'
down_revision: Union[str, Sequence[str], None] = 'e4a7c1d9b2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_polls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('chosen_option_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('date_polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_date_polls_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_date_polls_status'), ['status'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('author_member_id', sa.String(length=36), nullable=False),
    sa.Column('recipient_member_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_member_id'), ['author_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_recipient_member_id'), ['recipient_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_session_id'), ['session_id'], unique=False)

    op.create_table('date_options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('poll_id', sa.String(length=36), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('proposed_by_member_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['date_polls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposed_by_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'starts_at')
    )
    with op.batch_alter_table('date_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_date_options_poll_id'), ['poll_id'], unique=False)

    op.create_table('date_votes',
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('answer', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['date_options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id', 'member_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('date_votes')
    with op.batch_alter_table('date_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_date_options_poll_id'))

    op.drop_table('date_options')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_session_id'))
        batch_op.drop_index(batch_op.f('ix_comments_recipient_member_id'))
        batch_op.drop_index(batch_op.f('ix_comments_created_at'))
        batch_op.drop_index(batch_op.f('ix_comments_author_member_id'))

    op.drop_table('comments')
    with op.batch_alter_table('date_polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_date_polls_status'))
        batch_op.drop_index(batch_op.f('ix_date_polls_campaign_id'))

    op.drop_table('date_polls')
    # ### end Alembic commands ###
