"""verwaltung worker flags

Revision ID: f6a1c3d8e2b4
Revises: e5f9b2c7d1a3
Create Date: 2026-09-26 21:08:17.878750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a1c3d8e2b4'
down_revision: Union[str, Sequence[str], None] = 'e5f9b2c7d1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paused', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('local', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workers', schema=None) as batch_op:
        batch_op.drop_column('local')
        batch_op.drop_column('paused')

    # ### end Alembic commands ###
